language: java
group: stable
jdk:
- oraclejdk8

machine:
  environment:
    CC_TEST_REPORTER_ID: 96ae089d0a21104da1c39f0c0fd272b22a763c132e328a215cd90689f735eee2
    

plugins:
  sonar-java:
    enabled: true
    config:
      tests_patterns:
        - src/test/**

cache:
  directories:
  - $HOME/.m2

dependencies:
  post:
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - chmod +x ./cc-test-reporter

test:
  pre:
    - ./cc-test-reporter before-build

  post:
    - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT


script:
    - mvn clean verify
    - bash <(curl -s https://codecov.io/bash)
install:
- mvn -N io.takari:maven:wrapper
- ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

after_success:
  - bash <(curl -s https://codecov.io/bash)